### ISSUE TITLE
app-pipeline should not continue with stages when one has an error

### ISSUE THREAD

**Issue by thomasmckay** [RHsyseng/jenkins-on-openshift#93]
When a stage fails in the pipeline, the "Dev - Build Image" for example, the following stages should not be run. In the attached image the three stages after the failure all show green which, at least to me, is concerning. It leaves me wondering if something was in fact rolled out.
![openshift web console](https://user-images.githubusercontent.com/338096/32328581-c6cb31e2-bfb0-11e7-9ec3-4106768289fc.png)

**Comment by jcpowermac** [comment]
@thomasmckay it may look like it in OpenShift but in Jenkins it will show failure at `Dev - Build Image` and the following stages.

**Comment by codificat** [comment]
As Joe mentions this is a visualization bug in the console, and the log / accessing the Jenkins job should clarify what happened. 

The bug is already reported in
https://github.com/openshift/origin-web-console/issues/2509 so I believe we can close it here.
